Create ArrayList
KrArkadiy/CollectionsRealization pull request #2
Opened 2021-07-06 09:58 UTC by KrArkadiy

ArrayListRealization

2021-07-06 10:19 UTC, grom4er requested changes
20(!) замечаний

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    private int index = 0;
При создании объекта, типа ArrayList - каким значением будет инициализирована переменная

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +public class ArrayList<T> implements List<T>{
Вот тут ошибка стайла кода.
Есть в IDE команда, для того что исправить форматирование кода.

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    private T[] array;
Сделай Object. В таком случае тебе ничего не прийдеться кастить

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    private Class<T> cls;
Я так и не понял зачем тебе Эта переменная. В стандартной Oracle не нужно передавать никаких типов чтоб создать.

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    private int initialCapacity = 10;
Вот такие переменные всегда инициализуруються как final и пишутся с большими буквами

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +        if (index == array.length-1){
Чем add(T e) отличается от add(T e, int index) ?

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    public void add(T value, int index) {
Полностью переписать метод.
 arrayList.add("asd", -1);
 Моментально выдал NPE

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    public void clear() {
Достаточно создать новый массив

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    public void clear() {
Да и твой код не работает:
Потому что size никак не меняется.
В итоге у тебя будет что-то примерно так:
list.add(0)
list.add(1)
list.clear()
list.size == 2;

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +    public T get(int index) {
Нету проверки на валидность

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +        return 0;
-1 или ошибку

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +        T removedValue = array[index];
Нет проверки на валидность индекса

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +                removedValue = (T) array[i];
Зачем ты кастишь?

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +            if (array[i].equals(value)) {
NPE потенциальный

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +        return null;
Вернуть нужно элемент который удалил

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +                array[i] = null;
Нету изминение size

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +        T oldValue = array[index];
нет проверки на индекс

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +        T[] newArray = (T[]) Array.newInstance(this.cls, array.length * 2);
Для того чтоб оформить метод "меньше" ты добавил левую переменную.
Хотя с таким же успехом ты можешь достать любой элемент и получить его getClass - также костыльно, но уже не сверху - а под капотом.
но все равно не ок.

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +        System.arraycopy(array,0, newArray,0, index);
Молодца, тут добавить нечего.

2021-07-06 10:19 UTC, grom4er commented on src/main/java/ArrayList
> +                for (int i = size; i > index - 1; i--) {
Ты же используешь ArrayCopy, почему здесь цикл?

2021-07-06 21:05 UTC, KrArkadiy commented on src/main/java/ArrayList
> +public class ArrayList<T> implements List<T>{
import java.lang.reflect.Array;

public class ArrayList<T> implements List<T> {

2021-07-06 21:15 UTC, KrArkadiy commented on src/main/java/ArrayList
> +public class ArrayList<T> implements List<T>{
import java.lang.reflect.Array;

public class ArrayList<T> implements List<T> {

2021-07-06 21:16 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    private T[] array;
private Object[] array;

2021-07-06 21:16 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    private Class<T> cls;
исключено

2021-07-06 21:17 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        return 0;
@Override
    public int indexOf(T e) {
        for (int i = 0; i < array.length; i++) {
            if (array[i].equals(e)) {
                return i;
            }
        }
        return -1;
    }

2021-07-06 21:28 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        T[] newArray = (T[]) Array.newInstance(this.cls, array.length * 2);
private void resize() {
        Object[] newArray = new Object[array.length * 2];
        System.arraycopy(array,0, newArray,0, index);
        array = newArray;
    }

Я подумал, что возможно так, без newInstance будет правильнее

2021-07-06 21:30 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        System.arraycopy(array,0, newArray,0, index);
![55b0affc368a3cfe2a265cf0761f8b3c](https://user-images.githubusercontent.com/78499794/124669145-9630dc80-deba-11eb-8eac-46b123b87de6.png)

2021-07-06 21:42 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        T removedValue = array[index];
private void isCorrectIndex(int index){
        if(index < 0 || index >= size){
            System.out.printf("Incorrect index %d%n", index);
            throw new IndexOutOfBoundsException();
        }
    }

и непосредственно проверка 

 @Override
    public T remove(int index) {
        isCorrectIndex(index);

2021-07-06 21:42 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    public T get(int index) {
@Override
    public T get(int index) {
        isCorrectIndex(index);

2021-07-06 21:43 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        T oldValue = array[index];
@Override
    public T set(T e, int index) {
        isCorrectIndex(index);

2021-07-06 21:44 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    private int initialCapacity = 10;
private final int INITIAL_CAPACITY = 10;

2021-07-06 21:47 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    public void clear() {
@Override
    public void clear() {
        Object[] cleanArray = new Object[INITIAL_CAPACITY];
    }
    
    Точно, как-то не подумал про новый массив

2021-07-06 21:50 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    private int initialCapacity = 10;
private final int INITIAL_CAPACITY = 10;

2021-07-06 21:56 UTC, KrArkadiy commented on src/main/java/ArrayList
> +                removedValue = (T) array[i];
Идея ругается, если не закастить, потому что из массива мы получаем Object.

2021-07-06 22:06 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        return null;
Так в цикле возвращается удаленный элемент.
Или я что-то не понимаю?

2021-07-07 15:12 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    public void add(T value, int index) {
@Override
    public void add(T value, int index) {
        isCorrectIndex(index);
        if (isFull()) {
            resize();
        }
        System.arraycopy(array, index, array, index + 1, size - index);
        array[index] = value;
        size++;
    }

@Override
    public void add(T value) {
        add(value, size);
    }

2021-07-07 15:12 UTC, KrArkadiy commented on src/main/java/ArrayList
> +                for (int i = size; i > index - 1; i--) {
исключено, метод переписан

2021-07-07 15:24 UTC, KrArkadiy commented on src/main/java/ArrayList
> +            if (array[i].equals(value)) {
Переписал методы

@Override
    public T remove(int index) {
        isCorrectIndex(index);
        T removedValue = (T) array[index];
        System.arraycopy(array, index, array, index, size - index - 1);
        size--;
        return removedValue;
    }

    @Override
    public T remove(T value) {
        T removedValue;
        for (int i = 0; i < size; i++) {
            if (array[i].equals(value) && array[i] != null || array[i] == value) {
                removedValue = (T) array[i];
                return remove(i);
            }
        }
        throw new NoSuchElementException(String.format("Element %s not found.", value));
    }

2021-07-07 15:24 UTC, KrArkadiy commented on src/main/java/ArrayList
> +                array[i] = null;
Метод переписан

2021-07-07 15:25 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        return null;
Метод переписан

2021-07-07 15:26 UTC, KrArkadiy commented on src/main/java/ArrayList
> +    private int index = 0;
Исключена переменная

2021-07-07 15:26 UTC, KrArkadiy commented on src/main/java/ArrayList
> +        if (index == array.length-1){
Методы переписаны

2021-07-07 15:27 UTC, KrArkadiy commented
Вроде бы все исправил.

2021-07-08 08:50 UTC, merged